version: '3.1'
services:
  api-db:
    image: mysql
    ports:
      - "4306:3306"
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=roOzDXOKWz1DFU0u
      - MYSQL_HOST=localhost
    volumes:
      - "/data/mysql/stodioo/api:/var/lib/mysql"
      - "./tools/mysql/conf.d:/etc/mysql/conf.d"
      - "./tools/log:/var/log/mysql"
    security_opt:
      - seccomp:unconfined
  php:
    build:
      context: .
      dockerfile: ./tools/php/Dockerfile
    volumes:
      - "./api:/var/www/html"
      - "./tools/php/local.ini:/usr/local/etc/php/conf.d/local.ini"
  web-server:
    build:
      context: .
      dockerfile: ./tools/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - "./api:/var/www/html"
      - "./tools/nginx/conf.d:/etc/nginx/conf.d"
      - "./tools/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./tools/nginx/sites-enabled:/etc/nginx/sites-enabled"
